resources:
  - namespace.yaml

  - prometheus/configmap.yaml
  - prometheus/deployment.yaml
  - prometheus/service.yaml
  - prometheus/rbac.yaml

  - node-exporter/daemonset.yaml
  - node-exporter/service.yaml

  - kube-state-metrics/deployment.yaml
  - kube-state-metrics/service.yaml
  - kube-state-metrics/rbac.yaml

  - grafana/deployment.yaml
  - grafana/service.yaml
  - grafana/ingress.yaml

