resources:
  - namespace.yaml

  # cert-manager (REQUIRED for TLS)
  - cert-manager/

  # prometheus
  - prometheus/configmap.yaml
  - prometheus/deployment.yaml
  - prometheus/service.yaml
  - prometheus/rbac.yaml

  # exporters
  - node-exporter/
  - kube-state-metrics/

  # grafana
  - grafana/
