apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: user-service
  namespace: apps
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    traefik.ingress.kubernetes.io/router.entrypoints: web
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - user.13.201.174.4.nip.io
      secretName: user-service-tls
  rules:
    - host: user.13.201.174.4.nip.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: user-service
                port:
                  number: 80
