apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml

configMapGenerator:
  - name: platform-env
    envs:
      - ../../envs/global.env

vars:
  - name: EC2_PUBLIC_IP
    objref:
      kind: ConfigMap
      name: platform-env
      apiVersion: v1
    fieldref:
      fieldpath: data.EC2_PUBLIC_IP

