apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - agent-rbac.yaml
  - controller-rbac.yaml
  - pvc.yaml
  - service.yaml
  - deployment.yaml
  - endpoints.yaml
  - ingress.yaml
